# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5

      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: default

      - name: Build
        run: |
          npm install
          npm run build

      - name: Config Git
        uses: OleksiyRudenko/gha-git-credentials@v2
        with:
          email: 634750802@qq.com
          name: Jagger's Action

      - name: Deploy
        working-directory: dist
        run: |
          git init
          git add .
          git commit -m "deploy web"
          git remote add origin https://github.com/634750802/TypeTrain
          git push -f remote origin:gh-page
