# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5

      - name: Build
        run: npm run build

      - name: Run a multi-line script
        run: |
          cd dist
          git init
          git add .
          git commit -m "deploy web"
          git remote add origin https://github.com/634750802/TypeTrain
          git push -f origin gh-page
