# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5

      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: default

      - name: Build
        run: |
          npm install
          npm run build

      - name: Deploy
        working-directory: dist
        env: 
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "Init git" && \
          git init && \
          \
          echo "Init credentials" && \
          git config user.name "634750802" && \
          git config user.email "634750802@qq.com" && \
          \
          echo "Prepare git" && \
          git add . && \
          git commit -m "deploy web" && \
          git remote add origin https://$GITHUB_TOKEN$@github.com/634750802/TypeTrain.git && \
          \
          echo "Force push to gh-page" && \
          git push -f origin master:gh-page 
